language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"
    - SIMPLETEST_BASE_URL="http://localhost:8080"
    - SIMPLETEST_DB="sqlite://localhost/sites/default/files/.ht.sqlite"

addons:
  apt:
    packages:
    - postfix

before_install:
  # Update Composer
  - composer self-update

install:
  # Setup fake mailserver - Thanks to http://dropbucket.org/node/1761
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"
  # Install Drush
  - composer global require drush/drush 8.*
  # Move out of the module directory
  - cd ../..
  # Get Drupal
  - drush dl drupal-8.1.x --drupal-project-rename=drupal
  - cd drupal/modules
  - ln -s ${TRAVIS_BUILD_DIR} composer_security_checker
  - drush en composer_security_checker
  - cd ..
  - composer require sensiolabs/security-checker ~3.0.0
  # Start a web server using Drush.
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script:
  - cd core
  - phpunit ../modules/
