services:
  composer_security_checker.sensiolabs_security_checker:
    class: SensioLabs\Security\SecurityChecker
  composer_security_checker.security_checker_repository:
    class: Drupal\composer_security_checker\Repositories\SensioLabsSecurityCheckerRepository
    arguments: ['@config.factory', '@composer_security_checker.sensiolabs_security_checker']
