composer_security_checker.security_checker_report_controller_index:
  path: '/admin/reports/composer-security-report'
  defaults:
    _controller: '\Drupal\composer_security_checker\Controller\SecurityCheckerReportController::index'
    _title: 'Composer Security Checker Report'
  requirements:
    _permission: 'access composer security checker report'

composer_security_checker.composer_security_checker_settings_form:
  path: '/admin/config/composer-security-checker/settings'
  defaults:
    _form: '\Drupal\composer_security_checker\Form\ComposerSecurityCheckerSettingsForm'
    _title: 'Composer Security Checker Settings'
  requirements:
    _permission: 'access composer security checker settings'
  options:
    _admin_route: TRUE
