access composer security checker report:
  title: 'Access Composer Security Report'
  restrict access: true

access composer security checker settings:
  title: 'Access Composer Security settings'
  restrict access: true
